# Default values for typ.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

flask:
  deployment:
    name: flask
    replicaCount: 1
    image:
      repository: kondinskis/typ-api
      tag: latest
      pullPolicy: Always    
    env:
      flaskENV: development
      appSettings: project.config.DevelopmentConfig
      postgresUser:
        name: postgres-credentials
        key: user
      postgresPassword:
        name: postgres-credentials
        key: password
    restartPolicy: Always
  service:
    name: flask
    type: ClusterIP
    ports:
      port: 8080
      targetPort: 8080
      protocol: TCP

postgres:
  deployment:
    name: postgres
    labels:
      name: database
    replicaCount: 1
    image:
      repository: postgres
      tag: 10.4-alpine
      pullPolicy: Always
    env:
      postgresUser:
        name: postgres-credentials
        key: user
      postgresPassword:
        name: postgres-credentials
        key: password
      postgresDB:
        value: typ
    volume:
      name: postgres-volume-mount
      mountPath: /var/lib/postgresql/data
    volumes:
      name: postgres-volume-mount
      claimName: postgres-pvc
    restartPolicy: Always

  service:
    name: postgres
    type: ClusterIP
    ports:
      port: 5432
      targetPort: 5432
      protocol: TCP

secret:
  name: postgres-credentials
  type: Opaque
  data:
    user: c2FtcGxl
    password: cGxlYXNlY2hhbmdlbWU=

pv:
  name: postgres-pv
  labels:
    type: local
  spec:
    accessModes: ReadWriteOnce
  storage: 2Gi
  storageClassName: standard
  path: /data/postgres-pv

pvc:
  name: postgres-pvc
  labels:
    type: local
  spec:
    accessModes: ReadWriteOnce
  storage: 2Gi
  volumeName: postgres-pv
  storageClassName: standard

ingress:
  name: typ-ingress
  serviceName: flask
  servicePort: 8080
