apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flack.service.name }}
  labels:
    service: {{ .Values.flack.service.name }}
spec:
  selector:
    app: {{ .Values.flack.service.name }}
  type: {{ .Values.flack.service.type }}
  ports:
  - port: {{ .Values.flack.service.ports.port }}
    targetPort: {{ .Values.flack.service.ports.targetPort }}
    protocol: {{ .Values.flack.service.ports.protocol }}
    name: {{ .Values.flack.service.name }}
