apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  backend:
    serviceName: {{ .Values.ingress.serviceName }}
    servicePort: {{ .Values.ingress.servicePort }}
