apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    type: {{ .Values.pvc.labels.type }}
spec:
  accessModes:
    - {{ .Values.pvc.spec.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  volumeName: {{ .Values.pvc.volumeName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
