apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: {{ .Values.pv.labels.type }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  storageClassName: {{ .Values.pv.storageClassName }}
  accessModes:
    - {{ .Values.pv.spec.accessModes }}
  hostPath:
    path: "{{ .Values.pv.path }}"
