apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flack.secret.name }}
type: {{ .Values.flack.secret.type }}
data:
  user: {{ .Values.flack.secret.data.user }}
  password: {{ .Values.flack.secret.data.password }}
